global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'gitfortress'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:2345']