{
 "title": "gitfortress",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last run",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gitfortress\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> aggregateWindow(every: $__interval, fn: last)\n"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of remotes locally and remotely with number of synchronized repositories",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"gitfortress\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"local_repositories_count\" or r._field == \"synchronized_repositories_count\" or r._field == \"remote_repositories_count\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Cloned repositories count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"gitfortress\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"cloned_repositories_count\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Ignored repositories count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"gitfortress\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"ignored_repositories_count\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n"
    }
   ]
  }
 ]
}